"""
Plan a stratified SICC pull to n≥75 from the current n=13 sample.

This script does NOT execute a scrape — the ToS audit (data/tos_audit.md)
flagged that aggressive bulk-pulling under the current setup is exactly
what to halt until written permission from the Singapore Courts is in
place. What this script does:

1. Read the current 13 SICC entries from data/judgments.json.
2. Compute the gap from the audit-recommended target stratum
   (25 substantive / 25 jurisdiction-recognition / 25 costs-CMS = 75).
3. Write data/sicc_stratification_plan.md documenting:
   - the current distribution
   - the gap per stratum
   - a list of candidate URLs to add (drawn from elitigation.sg listing
     pages 2-N — left as TODO until the permission letter is sent)
   - the ToS gate that must be cleared first

After permission is granted, run scripts/fetch_sicc_more.py with the
target list filled in (and a higher n cap), then triage_sicc.py +
grade_borderline.py + merge_sicc.py.
"""

import json
from collections import Counter
from pathlib import Path


HERE = Path(__file__).resolve().parent.parent
JUDGMENTS = HERE / "data" / "judgments.json"
OUT = HERE / "data" / "sicc_stratification_plan.md"


# Audit-recommended target strata.
TARGET = {
    "substantive": {
        "n": 25,
        "claim_types": ("substantive_breach", "interpretation",
                        "summary_judgment"),
        "label": "Substantive commercial",
    },
    "jurisdiction_recognition": {
        "n": 25,
        "claim_types": ("jurisdictional_challenge",
                        "arbitration_recognition", "arbitration_enforcement"),
        "label": "Jurisdiction / recognition / enforcement",
    },
    "costs_cms": {
        "n": 25,
        "claim_types": ("costs_assessment", "case_management",
                        "permission_to_appeal", "interim_relief"),
        "label": "Costs / case management",
    },
}


def main():
    judgments = json.loads(JUDGMENTS.read_text())
    sicc = [j for j in judgments
            if j["tribunal"] == "Singapore International Commercial Court"]

    by_ct = Counter(j.get("claim_type", "other") for j in sicc)
    by_stratum = {k: 0 for k in TARGET}
    for j in sicc:
        ct = j.get("claim_type", "other")
        for stratum, spec in TARGET.items():
            if ct in spec["claim_types"]:
                by_stratum[stratum] += 1
                break

    lines = []
    lines.append("# SICC stratified-expansion plan (n=13 → n≥75)")
    lines.append("")
    lines.append("> Generated by `scripts/plan_sicc_expansion.py`. The actual "
                 "scrape is BLOCKED until written permission from the Singapore "
                 "Courts is on file (see `data/tos_audit.md` §3).")
    lines.append("")
    lines.append("## Current distribution (n=13)")
    lines.append("")
    lines.append("| claim_type                | n |")
    lines.append("|---------------------------|--:|")
    for ct, n in sorted(by_ct.items(), key=lambda x: -x[1]):
        lines.append(f"| {ct:<26}| {n} |")
    lines.append("")
    lines.append("## Mapped to target strata")
    lines.append("")
    lines.append("| Stratum                                    | Have | Need | Gap |")
    lines.append("|--------------------------------------------|-----:|-----:|----:|")
    for stratum, spec in TARGET.items():
        have = by_stratum[stratum]
        need = spec["n"]
        gap = max(0, need - have)
        lines.append(f"| {spec['label']:<42} | {have:>4} | {need:>4} | {gap:>3} |")

    total_gap = sum(max(0, TARGET[s]["n"] - by_stratum[s]) for s in TARGET)
    lines.append(f"| **Total gap**                              |      |      | **{total_gap}** |")
    lines.append("")

    # Candidate URLs — fetched listings (cached in data/raw/sicc/firecrawl/)
    # would normally be parsed here. We don't run the scrape; we document the
    # listing URLs that the next pull will need to consume.
    lines.append("## Source listing URLs (for permitted pull)")
    lines.append("")
    lines.append(
        "The eLitigation listing for SICC is paginated; the existing "
        "`scripts/fetch_sicc_more.py` already targets page 2. To reach "
        "n≥75, expand the page range to 1–N (with N depending on output "
        "volume). Listing pattern:"
    )
    lines.append("")
    lines.append("```")
    lines.append("https://www.elitigation.sg/gd/Home/Index"
                 "?Filter=SICC&YearOfDecision=All&"
                 "SortBy=DateOfDecision&CurrentPage={N}&SortAscending=False&"
                 "PageSize=0&Verbose=False&SearchQueryTime=0&"
                 "SearchTotalHits=0&SearchMode=True&SpanMultiplePages=False")
    lines.append("```")
    lines.append("")
    lines.append("## Pre-conditions before scrape")
    lines.append("")
    lines.append("1. Written permission from the Singapore Courts "
                 "registrar covering academic / research redistribution, "
                 "OR a confirmed scope of fair-dealing-only redistribution "
                 "in `LICENSE` (see `data/tos_audit.md` §3).")
    lines.append("2. `FIRECRAWL_KEY` env var set, or replace "
                 "`fetch_sicc_more.py` with a direct-fetch implementation "
                 "(eLitigation does not require an API key for individual "
                 "judgment pages).")
    lines.append("3. Stratification target list written to "
                 "`data/sicc_pull_targets.json` so the fetcher hits "
                 "judgments evenly across the three strata.")
    lines.append("")
    lines.append("## Re-scoring step")
    lines.append("")
    lines.append("After fetch, run:")
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/triage_sicc.py")
    lines.append("python3 scripts/grade_borderline.py     # SICC subset")
    lines.append("python3 scripts/merge_sicc.py")
    lines.append("python3 scripts/_verify_sicc_merge.py")
    lines.append("```")
    lines.append("")
    lines.append("Then update §4 of `paper.md` with revised SICC means and "
                 "re-run `python3 scripts/analyse_falsification.py` and "
                 "`python3 scripts/analyse_comparison.py` so the courts row "
                 "reflects the new SICC n.")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    print(f"total gap from current 13 to target 75: {total_gap}")


if __name__ == "__main__":
    main()
